// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RngHelpdesk.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RngHelpdesk.Infrastructure.Persistence.Contexts.ActorUserLinkRow", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorType")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ActorId", "ActorType");

                    b.ToTable("actor_user_links", "identity");
                });

            modelBuilder.Entity("RngHelpdesk.Infrastructure.Persistence.Contexts.AuthUserRow", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Username");

                    b.ToTable("auth_users", "identity");
                });

            modelBuilder.Entity("RngHelpdesk.Infrastructure.Persistence.Contexts.EventRecordRow", b =>
                {
                    b.Property<long>("GlobalPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GlobalPosition"));

                    b.Property<int>("EventSchemaVer")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StreamId")
                        .HasColumnType("integer");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreamVersion")
                        .HasColumnType("integer");

                    b.HasKey("GlobalPosition");

                    b.HasIndex("GlobalPosition")
                        .IsUnique();

                    b.HasIndex("StreamType", "StreamId", "StreamVersion")
                        .IsUnique();

                    b.ToTable("event_store", "eventstore");
                });

            modelBuilder.Entity("RngHelpdesk.Infrastructure.Persistence.Contexts.EventStreamRow", b =>
                {
                    b.Property<string>("StreamType")
                        .HasColumnType("text");

                    b.Property<int>("StreamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StreamType", "StreamId");

                    b.ToTable("event_streams", "eventstore");
                });

            modelBuilder.Entity("RngHelpdesk.Infrastructure.Persistence.Contexts.ProjectionCheckpointRow", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasColumnType("text");

                    b.Property<long>("LastPosition")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectionName");

                    b.ToTable("projection_checkpoints", "projections");
                });

            modelBuilder.Entity("RngHelpdesk.Infrastructure.Persistence.Contexts.RankThresholdRow", b =>
                {
                    b.Property<string>("Rank")
                        .HasColumnType("text");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Rank");

                    b.ToTable("rank_thresholds", "points");
                });
#pragma warning restore 612, 618
        }
    }
}
